# Generated by Django 5.2.10 on 2026-01-30 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField()),
                ('assessment_id', models.IntegerField()),
                ('question_id', models.IntegerField()),
                ('file_url', models.URLField()),
                ('expiry_date', models.DateField()),
                ('file_type', models.CharField(max_length=20)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='vendor_user_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
