# Generated by Django 4.2.27 on 2026-01-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidencefile_delete_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencefile',
            name='assessment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='org_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidencefile',
            name='uploaded_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
